# Generated by Django 4.2.2 on 2023-08-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='syllabus',
        ),
    ]
