# Generated by Django 4.2.2 on 2023-08-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lms', '0002_users_faculty_alter_users_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='faculty',
        ),
    ]
