# Generated by Django 4.2.2 on 2023-08-21 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lms', '0003_remove_users_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='Lms.users'),
        ),
    ]
