# Generated by Django 4.2.2 on 2023-08-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lms', '0004_users_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
